const TYPES = {
// send otp functionality types:
    SEND_OTP_LOADING:'SEND_OTP_LOADING',
    SEND_OTP_SUCCESS:'SEND_OTP_SUCCESS',
    SEND_OTP_FAILURE:'SEND_OTP_FAILURE',
    SEND_OTP_AGAIN:'SEND_OTP_AGAIN',

//verify otp functionality
VERIFY_OTP_LOADING:'VERIFY_OTP_LOADING',
VERIFY_OTP_SUCCESS:'VERIFY_OTP_SUCCESS',
VERIFY_OTP_FAILURE:'VERIFY_OTP_FAILURE',

//update email and phone
UPDATE_EMAIL_LOADING:'UPDATE_EMAIL_LOADING',
UPDATE_EMAIL_SUCCESS:'UPDATE_EMAIL_SUCCESS',
UPDATE_EMAIL_FAILURE:'UPDATE_EMAIL_FAILURE',

//Logout constant
LOGOUT_SUCCESS:'LOGOUT_SUCCESS',

//UPDATE USER PROFILE
UPDATE_PROFILE_SUCCESS:'UPDATE_PROFILE_SUCCESS',
};
export default TYPES;
