const TYPES = {
// send otp functionality types:
    SEND_OTP_LOADING:'SEND_OTP_LOADING',
    SEND_OTP_SUCCESS:'SEND_OTP_SUCCESS',
    SEND_OTP_FAILURE:'SEND_OTP_FAILURE',
    SEND_OTP_AGAIN:'SEND_OTP_AGAIN',

//verify otp functionality
VERIFY_OTP_LOADING:'VERIFY_OTP_LOADING',
VERIFY_OTP_SUCCESS:'VERIFY_OTP_SUCCESS',
VERIFY_OTP_FAILURE:'VERIFY_OTP_FAILURE',

//update email and phone
UPDATE_EMAIL_LOADING:'UPDATE_EMAIL_LOADING',
UPDATE_EMAIL_SUCCESS:'UPDATE_EMAIL_SUCCESS',
UPDATE_EMAIL_FAILURE:'UPDATE_EMAIL_FAILURE',

//Logout constant
LOGOUT_SUCCESS:'LOGOUT_SUCCESS',

//UPDATE USER PROFILE
UPDATE_PROFILE_SUCCESS:'UPDATE_PROFILE_SUCCESS',
//FETCH USER CARS
FETCH_USER_CAR_LOADING:'FETCH_USER_CAR_LOADING',
FETCH_USER_CAR_SUCCESS:'FETCH_USER_CAR_SUCCESS',
FETCH_USER_CAR_FAILURE:'FETCH_USER_CAR_FAILURE',

//FETCH CAR COMPANIES
FETCH_CAR_COMPANIES_LOADING:'FETCH_CAR_COMPANIES_LOADING',
FETCH_CAR_COMPANIES_SUCCESS:'FETCH_CAR_COMPANIES_SUCCESS',
FETCH_CAR_COMPANIES_FAILURE:'FETCH_CAR_COMPANIES_FAILURE',

//FETCH CAR BY COMPANY
FETCH_CAR_BY_COMPANY_LOADING:'FETCH_CAR_BY_COMPANY_LOADING',
FETCH_CAR_BY_COMPANY_SUCCESS:'FETCH_CAR_BY_COMPANY_SUCCESS',
FETCH_CAR_BY_COMPANY_FAILURE:'FETCH_CAR_BY_COMPANY_FAILURE',

//CREATE USER CAR
CREATE_USER_CAR_LOADING:'CREATE_USER_CAR_LOADING',
CREATE_USER_CAR_SUCCESS:'CREATE_USER_CAR_SUCCESS',
CREATE_USER_CAR_FAILURE:'CREATE_USER_CAR_FAILURE',

// ADD ADDRESS
ADD_ADDRESS_LOADING : 'ADD_ADDRESS_LOADING',
ADD_ADDRESS_SUCCESS : 'ADD_ADDRESS_SUCCESS',
ADD_ADDRESS_FAILURE : 'ADD_ADDRESS_FAILURE',

//FETCH ADDRESS
FETCH_ADDRESS_LOADING:'FETCH_ADDRESS_LOADING',
FETCH_ADDRESS_SUCCESS:'FETCH_ADDRESS_SUCCESS',
FETCH_ADDRESS_FAILURE:'FETCH_ADDRESS_FAILURE',

};



export default TYPES;
