export const typography = {
    bodySmall:{
        fontSize:14,
    },
    body:{
        fontSize:16,
    },
    bodyMedium:{
        fontSize:18,
        fontWeight:400,
    },
    bodyLarge:{
        fontSize:20,
        fontWeight:400,
    },
    leadPara:{
        fontSize:22,
        fontWeight:400,
    },
    h6:{
        fontSize:16,
        fontWeight:700,
    },
    h5:{
        fontSize:18,
        fontWeight:700,
    },
    h4:{
        fontSize:24,
        fontWeight:700,
    },
    h3:{
        fontSize:28,
        fontWeight:700,
    },
    h2:{
        fontSize:36,
        fontWeight:700,
    },
    h1:{
        fontSize:44,
        fontWeight:700,
    },
    display1:{
        fontSize:48,
        fontWeight:200,
    },
    display2:{
        fontSize:40,
        fontWeight:200,
    },
}